AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2023
  EC2 Instance with custom security group allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.  
Parameters:
  MyImageid:
    Description: Enter your Imageid
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'
  myKeypair:
    Description: Enter your keypair
    Type: AWS::EC2::KeyPair::KeyName
    Default: Tsinzi2  
Resources:
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0        
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref myKeypair
      ImageId: !Ref MyImageid
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref secGroupName
      UserData: !Base64 |
        #!/bin/bash -ex
        dnf update -y
        dnf install python3 -y
        dnf install python3-pip -y
        pip3 install flask
        dnf install git -y
        FOLDER="https://raw.githubusercontent.com/Tsinzi/AWS-projects-Victoria/main/Project-001-roman-numerals-converter/templates"
        cd /home/ec2-user
        wget -P templates ${FOLDER}/index.html
        wget -P templates ${FOLDER}/result.html
        wget https://raw.githubusercontent.com/Tsinzi/AWS-projects-Victoria/main/Project-001-roman-numerals-converter/app.py
        python3 app.py
      Tags:
        - Key: Name
          Value: !Sub vic-converter ${AWS::StackName}
Outputs:
  WebserverURL:
    Value: !Sub
      - http://${address}
      - address: !GetAtt myEC2Instance.PublicIp
